version: "3.9"

services:
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_USER=shop
      - POSTGRES_PASSWORD=shop
    networks:
      - appnet
  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn shop.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    #  Включает поддержку запуска напрямую с джанго, если убрать ports, то можно будет открыть только с nginx
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - static_volume:/app/src/staticfiles
    depends_on:
      - db
      - redis
    networks:
      - appnet
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks:
      - appnet
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/app/src/staticfiles
    depends_on:
      - app
    networks:
      - appnet

networks:
  appnet:

volumes:
  static_volume:
