# Generated by Django 4.1.7 on 2023-03-21 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100000)),
                ("image", models.ImageField(upload_to="images")),
                ("cost", models.PositiveIntegerField(verbose_name="Цена")),
                ("weight", models.PositiveIntegerField(verbose_name="Вес в граммах")),
                ("rating", models.PositiveIntegerField(verbose_name="Рейтинг")),
            ],
        ),
        migrations.CreateModel(
            name="OrderInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "warehouse_block",
                    models.CharField(max_length=1, verbose_name="Складской блок"),
                ),
                (
                    "mode_of_Shipment",
                    models.CharField(max_length=20, verbose_name="Способ отгрузки"),
                ),
                (
                    "customer_care_calls",
                    models.PositiveIntegerField(
                        verbose_name="Количество звонков, сделанных с запросом на отгрузку"
                    ),
                ),
                (
                    "prior_purchases",
                    models.PositiveIntegerField(
                        verbose_name="Количество предыдущих покупок"
                    ),
                ),
                (
                    "product_importance",
                    models.CharField(max_length=20, verbose_name="Важность продукта"),
                ),
                ("gender", models.CharField(max_length=1, verbose_name="Пол")),
                (
                    "discount_offered",
                    models.PositiveIntegerField(verbose_name="Скидка"),
                ),
                (
                    "reached_on_time",
                    models.PositiveIntegerField(
                        verbose_name="Достигнуто вовремя? 0 - вовремя и наоборот"
                    ),
                ),
                (
                    "id_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.product",
                        verbose_name="product ID",
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user ID",
                    ),
                ),
            ],
        ),
    ]
