# Generated by Django 4.1.7 on 2023-03-21 13:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderinfo",
            old_name="mode_of_Shipment",
            new_name="mode_of_shipment",
        ),
    ]
